spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springProjection?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-message: always